config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :sessions, only: [:new, :create, :destroy]
   get 'signup', to: 'users#new'
   get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'
  post 'signin', to: 'sessions#new'
  post 'create', to: 'sessions#create'
  post 'signout', to: 'sessions#destroy'

  root 'breweries#index'
  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'block', on: :member
  end
  end

app/views/saved_snippets/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratebeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navibar">
    <%= link_to 'breweries', breweries_path %>
    <%= link_to 'beers', beers_path %>
    <%= link_to 'ratings', ratings_path %>
    <%= link_to 'styles', styles_path %>
    <%= link_to 'users', users_path %>
    <%= link_to 'clubs', beer_clubs_path %>
    <%= link_to 'places', places_path %> |
    <% if current_user %>
      <%= link_to current_user.username, current_user %>
      <%= link_to 'logout', session_path, method: :delete %>
      <%= link_to 'join a club', new_membership_path %>
    <% else %>
      <%= link_to 'signin', signin_path %>
      <%= link_to 'signup', signup_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>